# Generated by Django 4.1.3 on 2022-11-25 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UserSetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user", models.IntegerField()),
                ("auto_bid_alert", models.IntegerField()),
                ("auto_bid_max_amount", models.IntegerField()),
            ],
        ),
    ]
