# Generated by Django 4.1.3 on 2022-11-28 06:09

from django.db import migrations


def add_settings(apps, schema_editor):
    UserSetting = apps.get_model('usersettings', 'UserSetting')
    UserSetting(user = 2, auto_bid_alert = 50, auto_bid_max_amount = 1000).save()
    UserSetting(user = 3, auto_bid_alert = 75, auto_bid_max_amount = 1500).save()


class Migration(migrations.Migration):

    dependencies = [
        ("usersettings", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(add_settings)
    ]
