# Generated by Django 4.1.3 on 2022-12-23 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersettings', '0002_auto_20221128_0609'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersetting',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
