# Generated by Django 4.1.3 on 2022-11-20 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('last_bid_user', models.IntegerField(blank=True, default=None, null=True)),
                ('last_bid_price', models.IntegerField(default=0)),
                ('closes_at', models.DateTimeField()),
            ],
            options={
                'ordering': ['closes_at'],
            },
        ),
    ]
