# Generated by Django 4.1.3 on 2022-11-19 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='last_bid_price',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='last_bid_user',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
